theme: jekyll-theme-cayman
title: Type Ia supernovae in the Near-Infrared
description: Pittsburgh, 2018 April 11-13
google_analytics: UA-108188963-1
show_downloads: false

$large-breakpoint: 64em !default;
$medium-breakpoint: 42em !default;

$header-heading-color: #aaa !default;
$header-bg-color: #159957 !default;
$header-bg-color-secondary: #155799 !default;

$section-headings-color: #159957 !default;
$body-text-color: #606c71 !default;
$body-link-color: #1e6bb8 !default;
$blockquote-text-color: #819198 !default;

$code-bg-color: #f3f6fa !default;
$code-text-color: #567482 !default;

$border-color: #dce6f0 !default;
$table-border-color: #e9ebec !default;
$hr-border-color: #eff0f1 !default;
